# Generated by Django 4.1.6 on 2023-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='avatar.jpg', upload_to='media/profile_pictures/'),
        ),
    ]
